### ISSUE TITLE
Esp32 Ethernet compatibility

### ISSUE THREAD

**Issue by tilchl** [khoih-prog/AsyncHTTPRequest_Generic#12]
Is your Library compatible with the Ethernet implementation on the esp32?

**Comment by khoih-prog** [comment]
Which Ethernet you're mentioning? LAN8720 or external Ethernet such as W5x00, ENC28J60?
Haven't tested any of those settings yet. **Currently not supporting**. 
Prerequisite is if Async is working seamlessly with Ethernet libraries. Hopefully in the future.
