### ISSUE TITLE
Unable to implement AsyncHTTPRequest_Generic in classes(.cpp and .h)

### ISSUE THREAD

**Issue by jalakamkiran** [khoih-prog/AsyncHTTPRequest_Generic#17]
### Describe the bug
I am trying to make a separate header file for my case of getting status of the relay from server. I am able to perfectly run the code if I keep all the code in the .ino file. But if I do the same using header files (.cpp and .h) compiler throws the multiple definitions errors for the same.

### Steps to Reproduce
Here is the code for the .h file
https://pastebin.com/Ns1RstVC

Here is the code for .cpp file
https://pastebin.com/K2Ak9eMG

Now when I make them as library or even in the same sketch folder it gives me the errors as follows
https://pastebin.com/LEmfi37P

### Expected behavior

The code should compile fine without conflicts with the c++ library of the esp32 arduino(which is the case I think).

### Actual behavior

The functions of xbuf_Impl.h are colliding with esp32 c++ function definitions(as per the logs). 

### Debug and AT-command log (if applicable)

https://pastebin.com/LEmfi37P

### Screenshots

![image](https://user-images.githubusercontent.com/39314292/123368953-628cb300-d59a-11eb-8bf0-4ea8cb2f7d02.png)

### Information

Please ensure to specify the following:

* Arduino IDE version  1.8.15
* `ESP32` Core Version 1.0.6 (esp32 wrover module is being used)
* Library to check status of relay and turn on automatically
* Download the code and include in the same folder as .ino file. Add include statement and it will be done.
  OS: Windows 10

**Comment by khoih-prog** [comment]
> I keep all the code in the .ino file. But if I do the same using header files (.cpp and .h) compiler throws the multiple definitions errors for the same.

How can you think this is a bug when you don't know what to do correctly. Please study some more before speaking something out.
