### ISSUE TITLE
How can I send https requests?

### ISSUE THREAD

**Issue by jitendra1607** [khoih-prog/AsyncHTTPRequest_Generic#18]
If i change http -> https then request fails "Can't send bad request". How can I send https requests?

`
requestOpenResult = request.open("GET", "https://worldtimeapi.org/api/timezone/America/Toronto.txt");
    
    if (requestOpenResult)
    {
      // Only send() if open() returns true, or crash
      request.send();
    }
    else
    {
      Serial.println("Can't send bad request");
    }
`

**Comment by khoih-prog** [comment]
> As the library's name implies, only HTTP is supported. No HTTPS.Have a look at

1. [HTTPS #9](https://github.com/khoih-prog/AsyncHTTPRequest_Generic/issues/9)
2. [HTTPS not supported? #2](https://github.com/khoih-prog/AsyncHTTPRequest_Generic/issues/2)
