### ISSUE TITLE
HTTPS Support

### ISSUE THREAD

**Issue by mdjavedakhtar** [khoih-prog/AsyncHTTPRequest_Generic#19]
hello
i think this does not handle https

  if (url.substring(0, 7).equalsIgnoreCase("HTTP://"))
  {
    hostBeg += 7;
  }
  else if (url.substring(0, 8).equalsIgnoreCase("HTTPS://"))
  {
    return false;
  }

for a project i need https badly can you help

**Comment by khoih-prog** [comment]
Thanks for testing the library.

But it's more helpful to us if you read the previous closed requests for HTTPS and save us some time to deal with the issue.

1. [HTTPS not supported? #2](https://github.com/khoih-prog/AsyncHTTPRequest_Generic/issues/2)
2. [HTTPS #9](https://github.com/khoih-prog/AsyncHTTPRequest_Generic/issues/9)
3. [How can I send https requests? #18](https://github.com/khoih-prog/AsyncHTTPRequest_Generic/issues/18)
