### ISSUE TITLE
Compilation for ESP32 in PIO requests STM32 framework files?

### ISSUE THREAD

**Issue by manuelgonzalvez** [khoih-prog/AsyncHTTPRequest_Generic#32]
Hi, just added the library via platformio.ini, but i guess it is failing to determine the board i am using, as it is requesting some STM32 Ethernet headers, which i do not have and do not plan to install. 

Is it strictly neccesary to download STM32 platform? 

Thanks!

**Comment by khoih-prog** [comment]
You have to get more knowledge about PIO, then edit to remove unnecessary dependencies out of `platformio.ini` or `library.json`.

This has nothing to do with this library, and I suggest next time ask in `Discussions` or `PIO Forum`
