### ISSUE TITLE
Unable to resolve Multiple Definitions issue

### ISSUE THREAD

**Issue by joegatling** [khoih-prog/AsyncHTTPRequest_Generic#7]
Hello, I am trying to get this library to compile, but I am encountering the multiple definitions linker issue that is mentioned in the documentation. I am having a bit of trouble with the specified workaround.

As far as I can follow, the instructions are:
1. Rename the **src** folder containing nothing but .h files to **src_h**
2. Rename the **src_cpp** folder to **src**

The issue is that the library seems to already have a folder called **src_h**, which seems to be a duplicate of **src**.

I have tried simply deleting the src folder and renaming src_cpp, but that results in the following error:
`fatal error: AsyncHTTPRequest_Generic.h: No such file or directory
 #include <AsyncHTTPRequest_Generic.h> 
                                       ^`

Attached is a screenshot of the folders I have.
<img width="1436" alt="Screen Shot 2020-12-29 at 15 08 50" src="https://user-images.githubusercontent.com/3136323/103319784-d5e8aa00-49e7-11eb-8c1d-a4980e777186.png">

Any advice on how to fix this would be greatly appreciated!

**Comment by khoih-prog** [comment]
It seems you've done something not fully correct as the error states that you have **no file `AsyncHTTPRequest_Generic.h` at all in `src` directory.**

Make sure the only remaining `src` directory contains these files 

![Selection_641](https://user-images.githubusercontent.com/57012152/103320155-52888200-4a02-11eb-845f-086a258fd0be.png)

> The issue is that the library seems to already have a folder called src_h, which seems to be a duplicate of src.

You can follows these steps (so obvious that I even didn't mentioned)

1. Delete the `src_h` directory.
2. Detele `src` directory
3. Rename `src_cpp` -> `src`

Remember also to close then reopen PIO to refresh.

**Comment by joegatling** [comment]
Oh great! Thanks for clearing that up for me.

regards
-Joe
